openapi: 3.0.3
info:
  title: LMS Gateway
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /monitoring/ping:
    get:
      tags: [ Monitoring ]
      summary: Проверяет, жив ли сервис
      description: Вернет pong, если сервис жив, иначе будем плакать.
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: pong
  /notes:
    get:
      tags: [ Notes ]
      summary: Returns all saved notes
      description:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags: [ Notes ]
      summary: Creates a note
      description:
      requestBody:
        description: Draft of a note.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteDraft'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
components:
  schemas:
    NoteDraft:
      required:
        - content
      type: object
      properties:
        content:
          type: string
    Note:
      type: object
      required:
        - id
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
