spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8080
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    url: /openapi/api.yml
    path: /swagger-ui.html
logging:
  level:
    root: INFO
    r2dbc: DEBUG
    sql: TRACE
    web: DEBUG
  group:
    r2dbc: org.springframework.r2dbc,org.springframework.data.r2dbc
