openapi: 3.0.3
info:
  title: LMS Monolith
  version: 0.0.1
servers:
  - url: /api/v1
paths:
  /monitoring/ping:
    get:
      tags: [ Monitoring ]
      summary: Проверяет, жив ли сервис
      description: Вернет pong, если сервис жив, иначе будем плакать.
      responses:
        200:
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: pong
