---
name: Markdown Check
on:
  pull_request:
    paths:
      - ".github/workflows/*"
      - ".markdownlint.yaml"
      - "**/*.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          config_file: .markdownlint.yaml
          files: "**/*.md"
          dot: true